# Generated by Django 5.1.4 on 2025-01-18 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpino3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LaharanaKaratra', models.CharField(max_length=100, verbose_name="Laharan'ny Karatra")),
                ('Anarana', models.CharField(max_length=250)),
                ('Fanampiny', models.CharField(max_length=255)),
                ('Teraka', models.PositiveIntegerField()),
                ('Taona', models.IntegerField(blank=True, null=True)),
                ('L_v', models.CharField(choices=[('L', 'Lahy'), ('V', 'Vavy')], max_length=1)),
                ('Antonasa', models.CharField(max_length=200)),
                ('Adresy', models.CharField(max_length=255)),
                ('Faritra', models.CharField(max_length=150)),
                ('Fiday', models.CharField(max_length=13, null=True)),
                ('TaonaNahatogavanaTaoAmpiagonana', models.IntegerField(default=0, null=True)),
                ('FiagonanaNiavina', models.CharField(blank=True, max_length=250, null=True)),
                ('batisa', models.CharField(choices=[('ENY', 'ENY'), ('TSY', 'TSY')], max_length=3)),
                ('taona_nanaovana_batysa', models.IntegerField(blank=True, null=True)),
                ('M_P', models.CharField(choices=[('P', 'Mpadray'), ('K', 'Kristianina')], max_length=1)),
                ('TaonaNahaMpandray', models.IntegerField(blank=True, default=0, null=True)),
                ('DatyNakanaKaratra', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Katekomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taompianarana', models.PositiveIntegerField()),
                ('Daty_Nidirana', models.DateField()),
                ('Mpino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mpino', to='Fitatanana.mpino3')),
            ],
        ),
        migrations.CreateModel(
            name='Adidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taona', models.IntegerField(default=2025)),
                ('J', models.IntegerField(default=0)),
                ('P_J', models.IntegerField(default=0)),
                ('J_Date', models.DateField(blank=True, null=True)),
                ('F', models.IntegerField(default=0)),
                ('P_F', models.IntegerField(default=0)),
                ('F_Date', models.DateField(blank=True, null=True)),
                ('M', models.IntegerField(default=0)),
                ('P_M', models.IntegerField(default=0)),
                ('M_Date', models.DateField(blank=True, null=True)),
                ('Av', models.IntegerField(default=0)),
                ('P_Av', models.IntegerField(default=0)),
                ('Av_Date', models.DateField(blank=True, null=True)),
                ('Ma', models.IntegerField(default=0)),
                ('P_Ma', models.IntegerField(default=0)),
                ('Ma_Date', models.DateField(blank=True, null=True)),
                ('Ji', models.IntegerField(default=0)),
                ('P_Ji', models.IntegerField(default=0)),
                ('Ji_Date', models.DateField(blank=True, null=True)),
                ('Ju', models.IntegerField(default=0)),
                ('P_Ju', models.IntegerField(default=0)),
                ('Ju_Date', models.DateField(blank=True, null=True)),
                ('Ag', models.IntegerField(default=0)),
                ('P_Ag', models.IntegerField(default=0)),
                ('Ag_Date', models.DateField(blank=True, null=True)),
                ('S', models.IntegerField(default=0)),
                ('P_S', models.IntegerField(default=0)),
                ('S_Date', models.DateField(blank=True, null=True)),
                ('Ak', models.IntegerField(default=0)),
                ('P_Ak', models.IntegerField(default=0)),
                ('Ac_Date', models.DateField(blank=True, null=True)),
                ('N', models.IntegerField(default=0)),
                ('P_N', models.IntegerField(default=0)),
                ('N_Date', models.DateField(blank=True, null=True)),
                ('D', models.IntegerField(default=0)),
                ('P_D', models.IntegerField(default=0)),
                ('D_Date', models.DateField(blank=True, null=True)),
                ('Fitabarany', models.IntegerField(blank=True, null=True)),
                ('Mpino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Fitatanana.mpino3')),
            ],
        ),
    ]
