# Generated by Django 5.1.4 on 2025-03-25 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitatanana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanamarihana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lohanteny', models.CharField(blank=True, max_length=250, null=True)),
                ('Fanamarihana', models.TextField(blank=True, max_length=3000, null=True)),
                ('F_Mpino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='F_Mpino', to='Fitatanana.mpino3')),
            ],
        ),
    ]
