# Generated by Django 5.1.4 on 2025-01-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolaNiditra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taona', models.PositiveIntegerField()),
                ('Daty', models.DateField()),
                ('Antony', models.CharField(max_length=250)),
                ('Vola', models.PositiveIntegerField()),
                ('Fanamarihana', models.TextField(verbose_name=900)),
            ],
        ),
        migrations.CreateModel(
            name='VolaNivoka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taona', models.PositiveIntegerField()),
                ('Daty', models.DateField()),
                ('Antony', models.CharField(max_length=250)),
                ('Vola', models.PositiveIntegerField()),
                ('Fanamarihana', models.TextField(verbose_name=900)),
            ],
        ),
    ]
